
import { BlockType } from './types';

export const CHUNK_SIZE = 16;
export const WORLD_HEIGHT = 112;
export const VIEW_DISTANCE = 2; // Reducido ligeramente para mayor fluidez en 4GB

export const BLOCK_COLORS: Record<BlockType, string> = {
  [BlockType.AIR]: 'transparent',
  [BlockType.GRASS]: '#5c9e31',
  [BlockType.DIRT]: '#866043',
  [BlockType.STONE]: '#7c7c7c',
  [BlockType.WOOD]: '#a47e54',
  [BlockType.LEAVES]: '#3a6b24',
  [BlockType.BEDROCK]: '#333333',
  [BlockType.WATER]: '#3b5ed9',
  [BlockType.SAND]: '#dbd3a2',
  [BlockType.LOG]: '#6a4d36',
  [BlockType.MUSHROOM_RED]: '#ff2222',
  [BlockType.MUSHROOM_BROWN]: '#8d6e63',
  [BlockType.TERRACOTTA_WHITE]: '#d1b1a1',
  [BlockType.TERRACOTTA_ORANGE]: '#a05325',
  [BlockType.TERRACOTTA_RED]: '#8f3d2e',
  [BlockType.TERRACOTTA_YELLOW]: '#ba8524',
  [BlockType.TERRACOTTA_BROWN]: '#4d3223',
  [BlockType.TERRACOTTA_LIGHT_GRAY]: '#876b62',
  [BlockType.CACTUS]: '#0f5e1b',
  [BlockType.FLOWER_RED]: '#ff3333',
  [BlockType.FLOWER_YELLOW]: '#ffdd33',
  [BlockType.LAVA]: '#ff5500',
  [BlockType.OBSIDIAN]: '#15101a',
  [BlockType.BUCKET_EMPTY]: '#a1a1a1',
  [BlockType.BUCKET_WATER]: '#3b5ed9',
  [BlockType.BUCKET_LAVA]: '#ff4500',
  [BlockType.BED]: '#e53935',
  [BlockType.TORCH]: '#ffaa00',
  [BlockType.DOOR]: '#5c3a21',
  [BlockType.CRAFTING_TABLE]: '#ab7d4d',
  [BlockType.COAL_ORE]: '#2a2a2a',
  [BlockType.IRON_ORE]: '#b08a6f',
  [BlockType.GOLD_ORE]: '#f3c72c',
  [BlockType.REDSTONE_ORE]: '#e62e2e',
  [BlockType.DIAMOND_ORE]: '#55e3e3',
  [BlockType.COPPER_ORE]: '#d17b4b',
  [BlockType.COPPER_BLOCK]: '#ca6a3f',
  [BlockType.OXIDIZED_COPPER]: '#4fa493',
  [BlockType.SWORD]: '#a1a1a1',
  [BlockType.PICKAXE]: '#8d6e63',
  [BlockType.AXE]: '#c7a480',
  [BlockType.SHOVEL]: '#df9c5c',
  [BlockType.SULFUR]: '#ecec13',
  [BlockType.JUKEBOX]: '#5a3d28',
  [BlockType.MUSIC_DISC_CAT]: '#00ffcc',
  [BlockType.MUSIC_DISC_CHIRP]: '#ff3366',
  [BlockType.MUSIC_DISC_BLOCKS]: '#ffcc00',
  [BlockType.MUSIC_DISC_MELLOHI]: '#aa33ff',
};

export const BLOCK_NAMES: Record<BlockType, string> = {
  [BlockType.AIR]: 'Aire',
  [BlockType.GRASS]: 'Césped',
  [BlockType.DIRT]: 'Tierra',
  [BlockType.STONE]: 'Piedra',
  [BlockType.WOOD]: 'Tablones de Madera',
  [BlockType.LEAVES]: 'Hojas',
  [BlockType.BEDROCK]: 'Lecho de Roca',
  [BlockType.WATER]: 'Agua',
  [BlockType.SAND]: 'Arena',
  [BlockType.LOG]: 'Tronco',
  [BlockType.MUSHROOM_RED]: 'Champiñón Rojo',
  [BlockType.MUSHROOM_BROWN]: 'Champiñón Marrón',
  [BlockType.TERRACOTTA_WHITE]: 'Terracota Blanca',
  [BlockType.TERRACOTTA_ORANGE]: 'Terracota Naranja',
  [BlockType.TERRACOTTA_RED]: 'Terracota Roja',
  [BlockType.TERRACOTTA_YELLOW]: 'Terracota Amarilla',
  [BlockType.TERRACOTTA_BROWN]: 'Terracota Marrón',
  [BlockType.TERRACOTTA_LIGHT_GRAY]: 'Terracota Gris Claro',
  [BlockType.CACTUS]: 'Cactus',
  [BlockType.FLOWER_RED]: 'Amapola (Flor Roja)',
  [BlockType.FLOWER_YELLOW]: 'Diente de León (Flor Amarilla)',
  [BlockType.LAVA]: 'Lava',
  [BlockType.OBSIDIAN]: 'Obsidiana',
  [BlockType.BUCKET_EMPTY]: 'Cubeta Vacía',
  [BlockType.BUCKET_WATER]: 'Cubeta con Agua',
  [BlockType.BUCKET_LAVA]: 'Cubeta con Lava',
  [BlockType.BED]: 'Cama',
  [BlockType.TORCH]: 'Antorcha',
  [BlockType.DOOR]: 'Puerta de Madera',
  [BlockType.CRAFTING_TABLE]: 'Mesa de Crafteo',
  [BlockType.COAL_ORE]: 'Mineral de Carbón',
  [BlockType.IRON_ORE]: 'Mineral de Hierro',
  [BlockType.GOLD_ORE]: 'Mineral de Oro',
  [BlockType.REDSTONE_ORE]: 'Mineral de Redstone',
  [BlockType.DIAMOND_ORE]: 'Mineral de Diamante',
  [BlockType.COPPER_ORE]: 'Mineral de Cobre',
  [BlockType.COPPER_BLOCK]: 'Bloque de Cobre',
  [BlockType.OXIDIZED_COPPER]: 'Bloque de Cobre Oxidado',
  [BlockType.SWORD]: 'Espada de Hierro (Herramienta)',
  [BlockType.PICKAXE]: 'Pico de Piedra (Herramienta)',
  [BlockType.AXE]: 'Hacha de Madera (Herramienta)',
  [BlockType.SHOVEL]: 'Pala de Tierra (Herramienta)',
  [BlockType.SULFUR]: 'Mineral de Azufre',
  [BlockType.JUKEBOX]: 'Tocadiscos',
  [BlockType.MUSIC_DISC_CAT]: 'Disco de Música (Cat)',
  [BlockType.MUSIC_DISC_CHIRP]: 'Disco de Música (Chirp)',
  [BlockType.MUSIC_DISC_BLOCKS]: 'Disco de Música (Blocks)',
  [BlockType.MUSIC_DISC_MELLOHI]: 'Disco de Música (Mellohi)',
};
